# Generated by Django 2.2.6 on 2019-11-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
