# Generated by Django 3.0.7 on 2020-06-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191103_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journeystop',
            name='actual_arrival_time',
        ),
        migrations.RemoveField(
            model_name='journeystop',
            name='actual_departure_time',
        ),
        migrations.AddField(
            model_name='journeystop',
            name='actual_arrival_delay',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='journeystop',
            name='actual_departure_delay',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='journey_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
