# Generated by Django 3.1.1 on 2020-10-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200610_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journeystop',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
