# Generated by Django 3.1.3 on 2020-12-23 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_huge_refactoring_stop_not_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='journey_id',
        ),
    ]
