# Generated by Django 3.1.5 on 2021-01-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_journey_remove_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeystop',
            name='actual_platform',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='journeystop',
            name='planned_platform',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
