# Generated by Django 3.1.14 on 2023-06-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('core', '0010_auto_20230613_2317'), ('core', '0011_auto_20230613_2331'), ('core', '0012_auto_20230613_2354')]

    dependencies = [
        ('core', '0009_auto_20210107_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark_type', models.CharField(max_length=50, null=True)),
                ('code', models.TextField(null=True)),
                ('subject', models.TextField(null=True)),
                ('text', models.TextField(null=True)),
                ('priority', models.IntegerField(null=True)),
                ('trip_id', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='journey',
            name='remarks',
            field=models.ManyToManyField(to='core.Remark'),
        ),
        migrations.AddField(
            model_name='journeystop',
            name='remarks',
            field=models.ManyToManyField(to='core.Remark'),
        ),
        migrations.AddField(
            model_name='journey',
            name='trip_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
