# Generated by Django 3.1.14 on 2023-09-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_journey_date_alter_journey_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='remarks',
            field=models.ManyToManyField(blank=True, to='core.Remark'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='stop',
            field=models.ManyToManyField(blank=True, through='core.JourneyStop', to='core.Stop'),
        ),
        migrations.AlterField(
            model_name='journeystop',
            name='remarks',
            field=models.ManyToManyField(blank=True, to='core.Remark'),
        ),
    ]
