# Generated by Django 4.2 on 2024-12-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230910_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='ifopt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
