---
nginx_vhosts:
  - listen: "8001"
    server_name: "{{ ansible_fqdn }}"
    root: "{{ fdg_static_root_path }}"
    index: "index.html"
    state: "present"
    filename: "fdg_static.conf"
    extra_parameters: |
      add_header Cache-Control "public, max-age=24h";
  - listen: "8002"
    server_name: "{{ ansible_fqdn }}"
    index: "index.html"
    state: "present"
    filename: "repo.conf"
    extra_parameters: |
      autoindex on;
      absolute_redirect off;

      location /debian/monitoring {
        alias /var/www/monitoring-check-plugins/repo/;
      }
nginx_remove_default_vhost: true
