# Generated by Django 2.2.6 on 2019-10-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_stopid_source_stop_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeystop',
            name='actual_arrival_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='journeystop',
            name='actual_departure_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='journeystop',
            name='planned_arrival_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='journeystop',
            name='planned_departure_time',
            field=models.DateTimeField(null=True),
        ),
    ]
