---
- name: move old fdg folder to new path
  command: mv /fdg /opt/
  ignore_errors: yes
  notify: delete virtualenv

- meta: flush_handlers

- name: create fgr folder
  file:
    path: /opt/fdg
    owner: www-data
    group: www-data
    recurse: yes
    state: directory

- name: create static files folder
  file:
    path: "{{ static_root }}"
    owner: www-data
    group: www-data
    recurse: yes
    state: directory

- name: create cache folder
  file:
    path: "{{ cache_root }}"
    owner: www-data
    group: www-data
    recurse: yes
    state: directory

- name: Install requirements for project
  apt:
    name:
      - python3-dev
      - python3-wheel
      - pdftk
    state: present

- include: python.yml
  become: yes
  become_method: su
  become_exe: sudo su
  become_user: www-data
  become_flags: '-s /bin/sh'
