---
- name: create fgr folder
  file:
    path: /fdg
    owner: www-data
    group: www-data
    recurse: yes
    state: directory

- name: create static files folder
  file:
    path: "{{ static_root }}"
    owner: www-data
    group: www-data
    recurse: yes
    state: directory

- include: python.yml
  become: yes
  become_method: su
  become_exe: sudo su
  become_user: www-data
  become_flags: '-s /bin/sh'
