---
- name: Clone repository from GitHub
  git:
    repo: https://github.com/Jugendhackt/FahrplanDatenGarten.git
    dest: /fdg
    force: yes

- name: Install requirements for project
  apt:
    pkg: ['python3-dev', 'python3-wheel']
    state: present

- name: Install pip requirements
  pip:
    requirements: /fdg/requirements.txt
    virtualenv: /fdg/.venv
    virtualenv_command: /usr/bin/python3 -m venv

- name: copy app configuration
  template:
    src: .env.j2
    dest: /fdg/.env

- name: collect django statics
  command: ../.venv/bin/python manage.py collectstatic --noinput
  args:
    chdir: /fdg/FahrplanDatenGarten

- name: migrate database
  command: ../.venv/bin/python manage.py migrate
  args:
    chdir: /fdg/FahrplanDatenGarten
