---
- name: Clone repository from GitHub
  git:
    repo: https://github.com/Jugendhackt/FahrplanDatenGarten.git
    dest: /fdg
    force: yes
    recursive: yes
  register: fdg_app_updated

- name: Install pip requirements
  pip:
    requirements: /fdg/requirements.txt
    virtualenv: /fdg/.venv
    virtualenv_command: /usr/bin/python3 -m venv
    extra_args: --upgrade

- name: copy app configuration
  template:
    src: env.cfg.j2
    dest: /fdg/FahrplanDatenGarten/env.cfg

- name: collect django statics
  command: ../.venv/bin/python manage.py collectstatic --noinput
  args:
    chdir: /fdg/FahrplanDatenGarten

- name: migrate database
  command: ../.venv/bin/python manage.py migrate
  args:
    chdir: /fdg/FahrplanDatenGarten
