---
- name: Install unattended-upgrades package
  apt:
    name: "unattended-upgrades"
    state: present

- name: Enable unattended upgrades
  template:
    src: unattended-upgrades/10periodic.j2
    dest: /etc/apt/apt.conf.d/10periodic

- name: Configure unattended upgrades
  template:
    src: unattended-upgrades/50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades

- name: Let restart server once a week
  cron:
    name: weekly restart unattended-upgrades
    weekday: "0"
    hour: "2"
    minute: "0"
    job: "/sbin/shutdown -r now"