---
celeryd_nodes: 4
wireguard_address: "fd59:974e:6ee8:10::3:1"
wireguard_private_key: "{{ lookup('passwordstore', 'infra/host/' + ansible_fqdn + '/wireguard') }}"
wireguard_public_key: "{{ lookup('passwordstore', 'infra/host/' + ansible_fqdn + '/wireguard subkey=public') }}"
