---
- name: Install gunicorn
  pip:
    name: "gunicorn==20.0.4"
    state: present
    virtualenv: "{{ fdg_base_path }}/.venv"

- name: Add Gunicorn service template
  template:
    src: "gunicorn.service.j2"
    dest: "/etc/systemd/system/gunicorn.service"

- name: Add tmpfiles/gunicorn config template
  template:
    src: "tmpfiles_gunicorn.conf.j2"
    dest: "/etc/tmpfiles.d/gunicorn.conf"

- name: Ensure gunicorn socket service is enabled and started
  systemd:
    name: "gunicorn.service"
    daemon_reload: yes
    enabled: yes
    state: restarted
