---
- name: Remove autossh
  apt:
    name: "autossh"
    state: absent

- name: Upload autossh service file
  file:
    path: "/etc/systemd/system/autossh.service"
    state: absent

- name: Ensure autossh service is started
  systemd:
    name: "autossh.service"
    state: stopped
    enabled: no
  ignore_errors: yes
