# Generated by Django 3.0.4 on 2020-03-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20191103_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('duration',
                 models.DurationField(
                     blank=True,
                     null=True)),
                ('stop',
                 models.ManyToManyField(
                     to='core.Stop')),
            ],
        ),
    ]
