---
postgresql_python_library: python3-psycopg2

postgresql_users:
  - name: "{{ lookup('passwordstore', 'infra/postgresql subkey=user') }}"
    password: "{{ lookup('passwordstore', 'infra/postgresql') }}"
postgresql_databases:
  - name: "fdg"
    owner: "{{ lookup('passwordstore', 'infra/postgresql subkey=user') }}"

postgresql_hba_entries:
  - { type: local, database: all, user: postgres, auth_method: peer }
  - { type: host, database: all, user: all, address: '{{ wireguard_fdg_net }}', auth_method: md5 }
