---
- name: Create celery user
  user:
    name: "celery"
    system: yes

- name: Add celeryd service template
  template:
    src: "celeryd.service.j2"
    dest: "/etc/systemd/system/celeryd.service"
  notify: reload celeryd service

- name: Add tmpfiles/celeryd config template
  template:
    src: "tmpfiles_celeryd.conf.j2"
    dest: "/etc/tmpfiles.d/celeryd.conf"
  notify: create tmpdirs

- name: Add logrotate config
  template:
    src: "logrotate.j2"
    dest: "/etc/logrotate.d/celeryd"
    mode: 0644

- name: Run previous handlers
  meta: flush_handlers

- name: Ensure celeryd service is enabled and started
  systemd:
    daemon_reload: yes
    name: "celeryd"
    enabled: yes
    state: started
