- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present

- name: Install resolvconf
  apt:
    name: resolvconf
    state: present

- name: Enable and start resolvconf service
  systemd:
    name: resolvconf
    enabled: yes
    state: started

- name: Add new nameserver to resolvconf
  blockinfile:
    path: /etc/resolvconf/resolv.conf.d/head
    insertbefore: BOF
    block: |
      nameserver ::1
      nameserver 127.0.0.1
  notify: Restart resolvconf service