---
- hosts: all
  tags: base
  roles:
    - worker_autossh
    - n0emis.base
    - em0lar.oh-my-zsh
    - jnv.unattended-upgrades

- hosts: all,!wireguard
  tags: wireguard
  roles:
    - n0emis.wireguard
  tasks:
    - name: Create wireguard_peer config for main wireguard server
      set_fact:
        wireguard_peer:
          public_key: "{{ wireguard_public_key }}"
          allowed_ips: "{{ wireguard_address }}/128"

- hosts: wireguard
  tags: wireguard
  pre_tasks:
    - name: Create wireguard peers config with host items
      set_fact:
        wireguard_wg_fdg_peers: "{{ wireguard_wg_fdg_peers | combine({ 'server_' + hostvars[item].ansible_fqdn: hostvars[item].wireguard_peer }) }}"
      when: "hostvars[item].ansible_fqdn is defined and hostvars[item].ansible_fqdn != ansible_fqdn"
      with_items: "{{ groups['all'] }}"
  roles:
    - n0emis.wireguard
  tasks:
    - name: Ensure forwarding of ipv4-packets is allowed
      sysctl:
          name: net.ipv4.ip_forward
          value: '1'
          state: present

    - name: Ensure forwarding of ipv6-packets is allowed
      sysctl:
          name: net.ipv6.conf.all.forwarding
          value: '1'
          state: present


- hosts: redis
  tags: redis
  roles:
    - geerlingguy.redis

- hosts: postgresql
  tags: postgresql
  roles:
    - geerlingguy.postgresql

- hosts: web,worker
  tags: web,worker,app
  roles:
    - fdg_app

- hosts: web
  tags: web
  roles:
    - fdg_app_gunicorn
    - geerlingguy.nginx
    - em0lar.traefik
  tasks:
    - name: Add dynamic traefik configs to server
      template:
        dest: "{{ traefik_dynamic_config_directory }}"
        src: "{{ item }}"
        owner: "{{ traefik_user }}"
        group: "{{ traefik_group }}"
      with_fileglob: '../files/web/traefik/*'

- hosts: worker
  tags: worker,dnsmasq
  roles:
    - worker_dnsmasq

- hosts: worker
  tags: worker,celery
  roles:
    - worker_celery

- hosts: celerybeat
  tags: celerybeat
  roles:
    - celerybeat
