---
# file: site.yml
- hosts: all
  roles:
    - general.packages
    - general.authentication
    - general.ohmyzsh
    - firewalld

- hosts: fdg
  tags: fdg
  roles:
    - fdg.redis
    - fdg.postgresql

- hosts: worker
  tags: worker
  roles:
    - fdg.app
    - worker.celery

- hosts: fdg
  tags: fdg
  roles:
    - fdg.celerybeat
    - fdg.gunicorn
    - fdg.reverse-proxy
