---
- hosts: all
  roles:
    - n0emis.base
    - general.packages
    - em0lar.oh-my-zsh
    - jnv.unattended-upgrades
#    - firewalld

- hosts: fdg
  tags: fdg
  roles:
    - fdg.redis
    - fdg.postgresql

- hosts: worker
  tags: worker
  roles:
    - fdg.app
    - worker.dnsmasq
    - worker.celery

- hosts: worker
  tags: worker
  roles:
    - worker.autossh

- hosts: fdg
  tags: fdg
  roles:
    - fdg.celerybeat
    - fdg.gunicorn
    - fdg.reverse-proxy
