---
- hosts: all
  tags: base
  roles:
    - n0emis.base
    - em0lar.oh-my-zsh
    - jnv.unattended-upgrades

- hosts: worker
  tags: base
  roles:
    - worker_autossh

- hosts: redis
  tags: redis
  roles:
    - geerlingguy.redis

- hosts: postgresql
  tags: postgresql
  roles:
    - geerlingguy.postgresql

- hosts: web,worker
  tags: web,worker,app
  roles:
    - fdg_app

- hosts: web
  tags: web
  roles:
    - fdg_app_gunicorn
    - geerlingguy.nginx
    - em0lar.traefik
  tasks:
    - name: Add dynamic traefik configs to server
      template:
        dest: "{{ traefik_dynamic_config_directory }}"
        src: "{{ item }}"
        owner: "{{ traefik_user }}"
        group: "{{ traefik_group }}"
      with_fileglob: '../files/web/traefik/*'

- hosts: worker
  tags: worker,dnsmasq
  roles:
    - worker_dnsmasq

- hosts: worker
  tags: worker,celery
  roles:
    - worker_celery

- hosts: celerybeat
  tags: celerybeat
  roles:
    - celerybeat
