http:
  routers:
    fdg_app_static-https:
      rule: "Host(`fahrplandatengarten.de`) && PathPrefix(`/static/`) || Host(`www.fahrplandatengarten.de`) && PathPrefix(`/static/`)"
      service: "services-fdg_app_static@file"
      entryPoints:
        - "https"
      tls:
        certResolver: "le_http"
      middlewares:
        - "fdg_app_static_prefixremove"
      priority: 2
    fdg_app-http:
      rule: "Host(`fahrplandatengarten.de`) || Host(`www.fahrplandatengarten.de`)"
      service: "services-fdg_app@file"
      entryPoints:
        - "http"
      middlewares:
        - "https_redirect"
    fdg_app-https:
      rule: "Host(`fahrplandatengarten.de`) || Host(`www.fahrplandatengarten.de`)"
      service: "services-fdg_app@file"
      entryPoints:
        - "https"
      tls:
        certResolver: "le_http"
      priority: 1
  services:
    services-fdg_app:
      loadBalancer:
        servers:
          - url: "http://localhost:8000"
    services-fdg_app_static:
      loadBalancer:
        servers:
          - url: "http://localhost:8001"
  middlewares:
    fdg_app_static_prefixremove:
      stripPrefix:
        prefixes:
          - "/static"
