http:
  routers:
    repo-http:
      rule: "Host(`repo.fahrplandatengarten.de`)"
      service: "services-repo@file"
      entryPoints:
        - "http"
      middlewares:
        - "https_redirect"
    repo-https:
      rule: "Host(`repo.fahrplandatengarten.de`)"
      service: "services-repo@file"
      entryPoints:
        - "https"
      tls:
        certResolver: "le_http"
  services:
    services-repo:
      loadBalancer:
        servers:
          - url: "http://localhost:8002"
