---
- name: collect django statics
  command: "{{ fdg_base_path }}/.venv/bin/python manage.py collectstatic --noinput"
  args:
    chdir: "{{ fdg_base_path }}/FahrplanDatenGarten"
  when: "'web' in group_names"

- name: migrate database
  command: "{{ fdg_base_path }}/.venv/bin/python manage.py migrate"
  args:
    chdir: "{{ fdg_base_path }}/FahrplanDatenGarten"
  when: "'web' in group_names"

- name: reload celeryd service
  systemd:
    name: "celeryd"
    state: reloaded
  when: "'worker' in group_names"
  ignore_errors: yes

- name: reload gunicorn service
  systemd:
    name: "gunicorn.service"
    state: reloaded
  when: "'web' in group_names"
  ignore_errors: yes

- name: restart celerybeat service
  systemd:
    name: "celerybeat"
    state: restarted
  when: "'celerybeat' in group_names"
  ignore_errors: yes
