# Generated by Django 3.1.14 on 2022-11-26 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_auto_20210107_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CoachJourneyStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagenreihung.coach')),
                ('journeystop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.journeystop')),
            ],
        ),
    ]
