# Generated by Django 3.1.5 on 2021-01-07 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_auto_20210107_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CoachJourneyStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255, null=True)),
                ('trainset_number', models.IntegerField(null=True)),
                ('sequence_number', models.IntegerField(null=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagenreihung.coach')),
                ('journeystop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.journeystop')),
            ],
        ),
    ]
