---

- name: Install nginx
  apt:
    pkg: ['nginx']

- name: Upload nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: reload nginx

- name: Install certbot
  apt:
    pkg: ['certbot', 'python3-certbot-nginx']
    update_cache: true
    state: present

- name: Change Let's Encrypt API to v2
  lineinfile:
    path: /etc/letsencrypt/cli.ini
    line: 'server = https://acme-v02.api.letsencrypt.org/directory'

- name: Register certbot certificate file
  stat:
    path: "/etc/letsencrypt/live/{{ ansible_fqdn }}/fullchain.pem"
  register: certbot_certificate_file_path

- name: Generate Certificates
  command:
    cmd: certbot certonly -d {{ ansible_fqdn }} -d fahrplandatengarten.de -d www.fahrplandatengarten.de --agree-tos --email webmaster@labcode.de -n --nginx
  notify: reload nginx
  when: not certbot_certificate_file_path.stat.exists