# Generated by Django 2.2.6 on 2019-10-05 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('journey_id', models.CharField(max_length=255)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Agency')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('ifopt', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StopName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=0)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Stop')),
            ],
        ),
        migrations.CreateModel(
            name='StopID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_stop_id', models.CharField(max_length=255)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Source')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Stop')),
            ],
        ),
        migrations.CreateModel(
            name='JourneyStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_arrival_time', models.DateTimeField()),
                ('planned_departure_time', models.DateTimeField()),
                ('actual_arrival_time', models.DateTimeField()),
                ('actual_departure_time', models.DateTimeField()),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Journey')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Stop')),
            ],
        ),
        migrations.AddField(
            model_name='journey',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Source'),
        ),
        migrations.AddField(
            model_name='journey',
            name='stop',
            field=models.ManyToManyField(through='core.JourneyStop', to='core.Stop'),
        ),
    ]
