# Generated by Django 2.2.6 on 2019-10-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191005_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopid',
            name='source_stop_id_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
