---
- name: Create celery user
  user:
    name: celery
    comment: celery

- name: Add celeryd service template
  template:
    src: celeryd.service.j2
    dest: /etc/systemd/system/celeryd.service

- name: Add tmpfiles/celeryd config template
  template:
    src: tmpfiles_celeryd.conf.j2
    dest: /etc/tmpfiles.d/celeryd.conf
  register: add_tmpfile

- name: Create tmpdirs
  command: systemd-tmpfiles --remove --create
  when: add_tmpfile.changed

- name: Ensure celeryd service is enabled and started
  systemd:
    daemon_reload: yes
    name: celeryd
    enabled: yes
    state: started

- name: reload celeryd service when fdg-app has changed
  systemd:
    name: celeryd
    state: restarted
  when: "fdg_app_updated.changed"
